# Generated by Django 4.1 on 2022-09-05 18:13

import applications.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('payment', applications.fields.IntegerRangeField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
