# Generated by Django 4.1 on 2022-09-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
