# Generated by Django 4.1 on 2022-09-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_deposit_date_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
